// NFT Gallery Component
// Generated by Cradle

'use client';

import { useNFTs } from '@/hooks/useChainData';
import type { NFTData } from '@/lib/data/data-client';

interface NFTGalleryProps {
  className?: string;
  columns?: number;
}

export function NFTGallery({ className, columns = 3 }: NFTGalleryProps) {
  const { data: nfts, isLoading, error } = useNFTs();
  
  if (isLoading) {
    return <div className={className}>Loading NFTs...</div>;
  }
  
  if (error) {
    return <div className={className}>Error loading NFTs</div>;
  }
  
  if (!nfts?.length) {
    return <div className={className}>No NFTs found</div>;
  }
  
  return (
    <div 
      className={className} 
      style={{ display: 'grid', gridTemplateColumns: `repeat(${columns}, 1fr)`, gap: '1rem' }}
    >
      {nfts.map((nft) => (
        <NFTCard key={`${nft.contractAddress}-${nft.tokenId}`} nft={nft} />
      ))}
    </div>
  );
}

function NFTCard({ nft }: { nft: NFTData }) {
  return (
    <div className="bg-zinc-800 rounded-lg overflow-hidden">
      {nft.image ? (
        <img src={nft.image} alt={nft.name} className="w-full aspect-square object-cover" />
      ) : (
        <div className="w-full aspect-square bg-zinc-700 flex items-center justify-center">
          <span className="text-zinc-500">No Image</span>
        </div>
      )}
      <div className="p-3">
        <p className="text-white font-medium truncate">{nft.name}</p>
        {nft.collection && (
          <p className="text-xs text-zinc-400 truncate">{nft.collection}</p>
        )}
      </div>
    </div>
  );
}

export default NFTGallery;