// Token List Component
// Generated by Cradle

'use client';

import { formatUnits } from 'viem';
import { useTokenBalances } from '@/hooks/useChainData';
import type { TokenData } from '@/lib/data/data-client';

interface TokenListProps {
  className?: string;
}

export function TokenList({ className }: TokenListProps) {
  const { data: tokens, isLoading, error } = useTokenBalances();
  
  if (isLoading) {
    return <div className={className}>Loading tokens...</div>;
  }
  
  if (error) {
    return <div className={className}>Error loading tokens</div>;
  }
  
  if (!tokens?.length) {
    return <div className={className}>No tokens found</div>;
  }
  
  return (
    <div className={className + ' space-y-2'}>
      {tokens.map((token) => (
        <TokenRow key={token.address} token={token} />
      ))}
    </div>
  );
}

function TokenRow({ token }: { token: TokenData }) {
  const balance = formatUnits(BigInt(token.balance), token.decimals);
  
  return (
    <div className="flex items-center justify-between p-3 bg-zinc-800 rounded-lg">
      <div className="flex items-center gap-3">
        {token.logo && (
          <img src={token.logo} alt={token.symbol} className="w-8 h-8 rounded-full" />
        )}
        <div>
          <p className="text-white font-medium">{token.symbol}</p>
          <p className="text-xs text-zinc-400">{token.name}</p>
        </div>
      </div>
      <p className="text-white font-mono">{Number(balance).toFixed(4)}</p>
    </div>
  );
}

export default TokenList;