// Chain Data Hooks
// Generated by Cradle

'use client';

import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAccount } from 'wagmi';
import type { Address } from 'viem';
import {
  getTokenBalances,
  getNFTs,
  getTransactionHistory,
  type TokenData,
  type NFTData,
} from '@/lib/data/data-client';

const CACHE_TIME = 60000;

export function useTokenBalances(address?: Address) {
  const { address: connectedAddress } = useAccount();
  const targetAddress = address ?? connectedAddress;
  
  return useQuery({
    queryKey: ['tokenBalances', targetAddress],
    queryFn: () => getTokenBalances(targetAddress!),
    enabled: !!targetAddress,
    staleTime: CACHE_TIME,
    
  });
}

export function useNFTs(address?: Address) {
  const { address: connectedAddress } = useAccount();
  const targetAddress = address ?? connectedAddress;
  
  return useQuery({
    queryKey: ['nfts', targetAddress],
    queryFn: () => getNFTs(targetAddress!),
    enabled: !!targetAddress,
    staleTime: CACHE_TIME,
  });
}

export function useTransactionHistory(address?: Address, limit = 50) {
  const { address: connectedAddress } = useAccount();
  const targetAddress = address ?? connectedAddress;
  
  return useQuery({
    queryKey: ['transactions', targetAddress, limit],
    queryFn: () => getTransactionHistory(targetAddress!, limit),
    enabled: !!targetAddress,
    staleTime: CACHE_TIME,
  });
}

export function useRefreshData() {
  const queryClient = useQueryClient();
  const { address } = useAccount();
  
  return () => {
    queryClient.invalidateQueries({ queryKey: ['tokenBalances', address] });
    queryClient.invalidateQueries({ queryKey: ['nfts', address] });
    queryClient.invalidateQueries({ queryKey: ['transactions', address] });
  };
}