// RPC Client Factory
// Generated by Cradle

import {
  createPublicClient,
  createWalletClient,
  http,
  webSocket,
  fallback,
  type PublicClient,
  type WalletClient,
  type Chain,
  type Transport,
} from 'viem';
import { arbitrum, arbitrumSepolia } from 'viem/chains';
import {
  getAllProviderEndpoints,
  RPC_CONFIG,
  type ProviderEndpoint,
} from './provider-config';

// Cache for clients
const clientCache = new Map<string, PublicClient>();

/**
 * Create transport from provider endpoint
 */
function createTransport(endpoint: ProviderEndpoint, useWebSocket: boolean): Transport {
  if (useWebSocket && endpoint.ws && RPC_CONFIG.enableWebSocket) {
    return webSocket(endpoint.ws, {
      reconnect: {
        attempts: RPC_CONFIG.retryAttempts,
        delay: 1000,
      },
    });
  }
  
  return http(endpoint.http, {
    retryCount: RPC_CONFIG.retryAttempts,
    retryDelay: 1000,
    timeout: 10000,
  });
}

/**
 * Create a fallback transport from all configured providers
 */
function createFallbackTransport(
  chain: 'arbitrum' | 'arbitrumSepolia',
  useWebSocket: boolean = false
): Transport {
  const endpoints = getAllProviderEndpoints(chain);
  
  if (endpoints.length === 0) {
    throw new Error('No RPC providers configured');
  }
  
  if (endpoints.length === 1) {
    return createTransport(endpoints[0], useWebSocket);
  }
  
  return fallback(
    endpoints.map(e => createTransport(e, useWebSocket)),
    { rank: true }
  );
}

/**
 * Get chain configuration
 */
function getChain(chainName: 'arbitrum' | 'arbitrumSepolia'): Chain {
  return chainName === 'arbitrum' ? arbitrum : arbitrumSepolia;
}

/**
 * Get a public client for reading chain data
 */
export function getPublicClient(
  chainName: 'arbitrum' | 'arbitrumSepolia' = 'arbitrum',
  options?: { useWebSocket?: boolean }
): PublicClient {
  const cacheKey = `${chainName}-${options?.useWebSocket ? 'ws' : 'http'}`;
  
  if (clientCache.has(cacheKey)) {
    return clientCache.get(cacheKey)!;
  }
  
  const chain = getChain(chainName);
  const transport = createFallbackTransport(chainName, options?.useWebSocket);
  
  const client = createPublicClient({
    chain,
    transport,
    batch: {
      multicall: true,
    },
  });
  
  clientCache.set(cacheKey, client);
  return client;
}

/**
 * Get a wallet client for signing transactions
 */
export function getWalletClient(
  chainName: 'arbitrum' | 'arbitrumSepolia' = 'arbitrum'
): WalletClient {
  const chain = getChain(chainName);
  const transport = createFallbackTransport(chainName, false);
  
  return createWalletClient({
    chain,
    transport,
  });
}

/**
 * Clear the client cache (useful when provider health changes)
 */
export function clearClientCache(): void {
  clientCache.clear();
}