// RPC Provider Configuration
// Generated by Cradle

import { arbitrum, arbitrumSepolia } from 'viem/chains';

export type ProviderName = 'alchemy' | 'quicknode' | 'infura' | 'ankr' | '1rpc' | 'public';

export interface ProviderEndpoint {
  name: ProviderName;
  http: string;
  ws?: string;
  priority: number;
  rateLimit?: number; // requests per second
  requiresKey: boolean;
}

// Chain configurations
export const CHAIN_CONFIG = {
  arbitrum: {
    id: arbitrum.id,
    name: 'Arbitrum One',
    isTestnet: false,
  },
  arbitrumSepolia: {
    id: arbitrumSepolia.id,
    name: 'Arbitrum Sepolia',
    isTestnet: true,
  },
} as const;

// Provider endpoint templates
const PROVIDER_TEMPLATES: Record<ProviderName, {
  arbitrum: { http: string; ws?: string };
  arbitrumSepolia: { http: string; ws?: string };
  requiresKey: boolean;
  rateLimit?: number;
}> = {
  alchemy: {
    arbitrum: {
      http: 'https://arb-mainnet.g.alchemy.com/v2/{API_KEY}',
      ws: 'wss://arb-mainnet.g.alchemy.com/v2/{API_KEY}',
    },
    arbitrumSepolia: {
      http: 'https://arb-sepolia.g.alchemy.com/v2/{API_KEY}',
      ws: 'wss://arb-sepolia.g.alchemy.com/v2/{API_KEY}',
    },
    requiresKey: true,
    rateLimit: 330, // ~330 CU/s on free tier
  },
  quicknode: {
    arbitrum: {
      http: '{ENDPOINT}',
      ws: '{ENDPOINT}'.replace('https://', 'wss://'),
    },
    arbitrumSepolia: {
      http: '{ENDPOINT}',
      ws: '{ENDPOINT}'.replace('https://', 'wss://'),
    },
    requiresKey: true,
    rateLimit: 25,
  },
  infura: {
    arbitrum: {
      http: 'https://arbitrum-mainnet.infura.io/v3/{API_KEY}',
      ws: 'wss://arbitrum-mainnet.infura.io/ws/v3/{API_KEY}',
    },
    arbitrumSepolia: {
      http: 'https://arbitrum-sepolia.infura.io/v3/{API_KEY}',
      ws: 'wss://arbitrum-sepolia.infura.io/ws/v3/{API_KEY}',
    },
    requiresKey: true,
    rateLimit: 10,
  },
  ankr: {
    arbitrum: {
      http: 'https://rpc.ankr.com/arbitrum/{API_KEY}',
      ws: 'wss://rpc.ankr.com/arbitrum/ws/{API_KEY}',
    },
    arbitrumSepolia: {
      http: 'https://rpc.ankr.com/arbitrum_sepolia/{API_KEY}',
    },
    requiresKey: false, // API key optional
    rateLimit: 30,
  },
  '1rpc': {
    arbitrum: {
      http: 'https://1rpc.io/arb',
    },
    arbitrumSepolia: {
      http: 'https://1rpc.io/arb-sepolia',
    },
    requiresKey: false,
    rateLimit: 10,
  },
  public: {
    arbitrum: {
      http: 'https://arb1.arbitrum.io/rpc',
    },
    arbitrumSepolia: {
      http: 'https://sepolia-rollup.arbitrum.io/rpc',
    },
    requiresKey: false,
    rateLimit: 5,
  },
};

/**
 * Get the RPC endpoint for a provider
 */
export function getProviderEndpoint(
  provider: ProviderName,
  chain: 'arbitrum' | 'arbitrumSepolia' = 'arbitrum'
): ProviderEndpoint {
  const template = PROVIDER_TEMPLATES[provider];
  const chainConfig = template[chain];
  
  let http = chainConfig.http;
  let ws = chainConfig.ws;
  
  // Replace API key placeholders
  if (provider === 'alchemy') {
    const key = process.env.NEXT_PUBLIC_ALCHEMY_API_KEY ?? '';
    http = http.replace('{API_KEY}', key);
    ws = ws?.replace('{API_KEY}', key);
  } else if (provider === 'quicknode') {
    const endpoint = process.env.NEXT_PUBLIC_QUICKNODE_ENDPOINT ?? '';
    http = endpoint;
    ws = endpoint.replace('https://', 'wss://');
  } else if (provider === 'infura') {
    const key = process.env.NEXT_PUBLIC_INFURA_API_KEY ?? '';
    http = http.replace('{API_KEY}', key);
    ws = ws?.replace('{API_KEY}', key);
  } else if (provider === 'ankr') {
    const key = process.env.NEXT_PUBLIC_ANKR_API_KEY ?? '';
    http = key ? http.replace('{API_KEY}', key) : http.replace('/{API_KEY}', '');
    ws = key && ws ? ws.replace('{API_KEY}', key) : undefined;
  }
  
  // Priority based on configuration
  const allProviders: ProviderName[] = ['alchemy', 'public'];
  const priority = allProviders.indexOf(provider);
  
  return {
    name: provider,
    http,
    ws,
    priority: priority >= 0 ? priority : 999,
    rateLimit: template.rateLimit,
    requiresKey: template.requiresKey,
  };
}

/**
 * Get all configured provider endpoints sorted by priority
 */
export function getAllProviderEndpoints(
  chain: 'arbitrum' | 'arbitrumSepolia' = 'arbitrum'
): ProviderEndpoint[] {
  const providers: ProviderName[] = ['alchemy', 'public'];
  
  return providers
    .map(p => getProviderEndpoint(p, chain))
    .filter(p => !p.requiresKey || p.http.length > 50) // Filter out unconfigured providers
    .sort((a, b) => a.priority - b.priority);
}

// Export configuration
export const RPC_CONFIG = {
  primaryProvider: 'alchemy' as ProviderName,
  fallbackProviders: ['public'] as ProviderName[],
  enableWebSocket: true,
  healthCheckInterval: 30000,
  retryAttempts: 3,
  privacyMode: false,
};